services:

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  singlestore:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.singlestore
    volumes:
      - singlestore_data:/var/lib/memsql
    environment:
      ROOT_PASSWORD: change-me

  nearai-hub:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.hub
    ports:
      - 8081:8081
    environment:
      SERVER_ENVIRONMENT: local
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: kholinar-registry
      S3_PREFIX: hub
      DATABASE_HOST: singlestore
      DATABASE_USER: root
      DATABASE_PASSWORD: change-me
      DATABASE_NAME: hub

volumes:
  singlestore_data:
  minio_data:
