name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: pipx install poetry

    - name: Get Poetry cache dir
      id: poetry-cache
      run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.poetry-cache.outputs.dir }}
        key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ matrix.python-version }}-

    - name: Install Codespell
      run: pip install codespell

    - name: Run Codespell
      run: codespell --config .codespellrc

    - name: check lock file for inconsistencies
      run: poetry check --lock

    - name: Install dependencies
      run: poetry install --extras explatform --extras hub

    - name: Lint Check
      run: ./scripts/lint_check.sh

    - name: Format Check
      run: ./scripts/format_check.sh

    - name: Type Check
      run: ./scripts/type_check.sh

    - name: Build Site
      run: ./scripts/build_mkdocs.sh

  integration:
    runs-on: integration
    timeout-minutes: 30
    environment: NearAI CI
    steps:

    - name: Install pv
      run: |
        sudo apt-get update
        sudo apt-get install -y pv

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
    
    - name: Docker Cache
      uses: actions/cache@v4
      with:
        path: /tmp/docker-cache
        key: ${{ runner.os }}-docker-cache-${{ hashFiles('**/.docker/**') }}
        restore-keys: |
          ${{ runner.os }}-docker-cache-
    
    - name: Load Images
      run: |
        for tar in /tmp/docker-cache/*.tar; do
          [ -f "$tar" ] && docker load -i "$tar" || true
        done

    - name: Build nearai_base Image
      run: |
        docker compose -f .docker/compose-e2e.yml build nearai_base

    - name: Save nearai_base Image
      run: |
        mkdir -p /tmp/docker-cache
        docker save nearai_base | pv -s $(docker image inspect nearai_base --format='{{.Size}}') > /tmp/docker-cache/nearai_base.tar
    
    - name: Pull Docker Images
      run: |
        docker compose -f .docker/compose-e2e.yml pull

    - name: Build Docker Images
      run: |
        docker compose -f .docker/compose-e2e.yml build
      env:
        NEARAICI_SIGNATURE: ${{ secrets.NEARAICI_SIGNATURE }}

    - name: Start Docker Compose
      run: docker compose -f .docker/compose-e2e.yml up -d
      env:
        SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}

    - name: Exec Integration Tests
      run: |
        sleep 60
        docker compose -f .docker/compose-e2e.yml logs
        docker exec docker-ci-1 poetry run pytest -m integration ./e2e/
    
    - name: Stop Docker Compose
      run: docker compose -f .docker/compose-e2e.yml down