name: Release

on:
  workflow_dispatch:
    inputs:
      make-release:
        description: 'Make a release'
        required: true
        default: 'false'
        type: boolean
      publish-pypi:
        description: 'Publish to PyPI'
        required: true
        default: 'false'
        type: boolean
      publish-docs:
        description: 'Publish to GitHub Pages'
        required: true
        default: 'false'
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install poetry
      run: pipx install poetry

    - name: Install Codespell
      run: pip install codespell

    - name: Run Codespell
      run: codespell --config .codespellrc

    - name: check lock file for inconsistencies
      run: poetry check --lock

    - name: Install dependencies
      run: poetry install --extras explatform --extras hub

    - name: Lint Check
      run: ./scripts/lint_check.sh

    - name: Format Check
      run: ./scripts/format_check.sh

    - name: Type Check
      run: ./scripts/type_check.sh

    - name: Bump version and generate changelog
      uses: commitizen-tools/commitizen-action@master
      with:
        changelog_increment_filename: body.md
      if: ${{ github.event.inputs.make-release == 'true' }}
    
    - name: Create release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.REVISION }}
        body_path: "body.md"
      if: ${{ github.event.inputs.make-release == 'true' }}
    
    - name: Build site
      run: ./scripts/build_mkdocs.sh
      if: ${{ github.event.inputs.publish-docs == 'true' }}
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./site
      if: ${{ github.event.inputs.publish-docs == 'true' }}
      
    - name: Build package
      run: poetry build
      if: ${{ github.event.inputs.publish-pypi == 'true' }}
      
    - name: Publish to PyPI
      run: poetry publish --build
      if: ${{ github.event.inputs.publish-pypi == 'true' }}